version: '3'

services:
  database:
    container_name: database
    image: mysql:latest
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
#    volumes:
#      - db-vol:/var/lib/mysql
#volumes:
#  db-vol:
